package it.unibo.samplejavafx.mvc.model.replay;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import it.unibo.samplejavafx.mvc.model.chessboard.BoardObserver;
import it.unibo.samplejavafx.mvc.model.entity.Entity;
import it.unibo.samplejavafx.mvc.model.point2d.Point2D;

import java.util.function.Supplier;

/**
 * Records game events into a GameHistory.
 * Filters out redundant events generated by the internal logic of ChessBoardImpl.
 */
public final class GameHistoryRecorder implements BoardObserver {

    private static final String UNKNOWN = "Unknown";
    private final GameHistory history;
    private final Supplier<Integer> turnSupplier;

    /**
     * @param turnSupplier a supplier that provides the current turn number.
     */
    public GameHistoryRecorder(final Supplier<Integer> turnSupplier) {
        this.history = new GameHistory();
        this.turnSupplier = turnSupplier;
    }

    /**
     * @return the recorded history.
     */
    @SuppressFBWarnings("EI_EXPOSE_REP")
    public GameHistory getHistory() {
        return history;
    }

    @Override
    public void onEntityAdded(final Point2D pos, final Entity entity) {
        history.addEvent(new SpawnEvent(turnSupplier.get(), entity, pos));
    }

    @Override
    public void onEntityRemoved(final Point2D pos, final Entity entity) {
        history.addEvent(new DespawnEvent(turnSupplier.get(), entity, pos));
    }

    @Override
    public void onEntityMoved(final Point2D from, final Point2D to, final Entity entity) {
        // Use the provided entity directly, avoiding "Unknown"
        final String entityName = entity.getName();
        final var entityColor = entity.getPlayerColor();
        Entity capturedEntity = null;

        // Clean up redundant Spawn/Despawn events generated by this move.
        // The typical sequence is: Despawn(from), [Despawn(to) if capture], Spawn(to).
        // We check the last few events to remove them.

        // 1. Remove Spawn at 'to' (The arrival of the mover)
        if (history.getLastEvent() instanceof SpawnEvent spawn && spawn.position().equals(to)) {
            history.removeLastEvent();
        }

        // 2. Remove Despawn at 'from' (The departure of the mover)
        // Note: Sometimes Despawn(to) might be in between if capture happened
        if (history.getLastEvent() instanceof DespawnEvent despawn && despawn.position().equals(from)) {
             history.removeLastEvent();
        }

        // 3. Remove Despawn at 'to' (The victim/capture)
        // Check again for Despawn at 'to' which might be the capture
        if (history.getLastEvent() instanceof DespawnEvent despawn && despawn.position().equals(to)) {
             capturedEntity = despawn.entity();
             history.removeLastEvent();
        }

        // Check again for Despawn at 'from' if it was pushed down by capture
        if (history.getLastEvent() instanceof DespawnEvent despawn && despawn.position().equals(from)) {
             history.removeLastEvent();
        }

        history.addEvent(new MoveEvent(turnSupplier.get(), entityName, entityColor, from, to, capturedEntity));
    }

    @Override
    public void onEntityMoved(final Point2D from, final Point2D to) {
        // Intentionally empty to avoid duplicate events.
        // ChessBoardImpl calls onEntityMoved(from, to, entity) which handles the logic.
    }

    @Override
    public void onEntityEaten(final Point2D from, final Point2D to) {
        // Intentionally empty. Captures are handled by checking Despawn events in onEntityMoved.
    }
}
