package it.unibo.samplejavafx.mvc.model.replay;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import it.unibo.samplejavafx.mvc.model.chessboard.BoardObserver;
import it.unibo.samplejavafx.mvc.model.entity.Entity;
import it.unibo.samplejavafx.mvc.model.point2d.Point2D;

import java.util.function.Supplier;
import java.util.List;

/**
 * Records game events into a GameHistory.
 * Filters out redundant events generated by the internal logic of ChessBoardImpl.
 */
public final class GameHistoryRecorder implements BoardObserver {

    private final GameHistory history;
    private final Supplier<Integer> turnSupplier;

    /**
     * @param turnSupplier a supplier that provides the current turn number.
     */
    public GameHistoryRecorder(final Supplier<Integer> turnSupplier) {
        this.history = new GameHistory();
        this.turnSupplier = turnSupplier;
    }

    /**
     * @return the recorded history.
     */
    @SuppressFBWarnings("EI_EXPOSE_REP")
    public GameHistory getHistory() {
        return history;
    }

    @Override
    public void onEntityAdded(final Point2D pos, final Entity entity) {
        if (history.getLastEvent() instanceof DespawnEvent despawn && despawn.position().equals(pos)) {
            final List<GameEvent> events = history.getEvents();
            if (events.size() >= 2) {
                final GameEvent potentialMove = events.get(events.size() - 2);
                if (potentialMove instanceof MoveEvent move 
                        && move.to().equals(pos)
                        && move.entityName().equals(despawn.entity().getName())
                        && move.entityColor() == despawn.entity().getPlayerColor()) {
                    
                    history.removeLastEvent();
                    history.removeLastEvent();
                    final MoveEvent mergedMove = new MoveEvent(
                        move.turn(),
                        move.entityName(),
                        move.entityColor(),
                        move.from(),
                        move.to(),
                        move.capturedEntity(),
                        entity,
                        despawn.entity()
                    );
                    
                    history.addEvent(mergedMove);
                    return;
                }
            }
        }
        
        history.addEvent(new SpawnEvent(turnSupplier.get(), entity, pos));
    }

    @Override
    public void onEntityRemoved(final Point2D pos, final Entity entity) {
        history.addEvent(new DespawnEvent(turnSupplier.get(), entity, pos));
    }

    @Override
    public void onEntityMoved(final Point2D from, final Point2D to, final Entity entity) {
        final String entityName = entity.getName();
        final var entityColor = entity.getPlayerColor();
        Entity capturedEntity = null;

        if (history.getLastEvent() instanceof SpawnEvent spawn && spawn.position().equals(to)) {
            history.removeLastEvent();
        }

        if (history.getLastEvent() instanceof DespawnEvent despawn && despawn.position().equals(from)) {
             history.removeLastEvent();
        }

        if (history.getLastEvent() instanceof DespawnEvent despawn && despawn.position().equals(to)) {
             capturedEntity = despawn.entity();
             history.removeLastEvent();
        }

        if (history.getLastEvent() instanceof DespawnEvent despawn && despawn.position().equals(from)) {
             history.removeLastEvent();
        }

        history.addEvent(new MoveEvent(turnSupplier.get(), entityName, entityColor, from, to, capturedEntity));
    }

}
