package it.unibo.samplejavafx.mvc.model.replay;

import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
import it.unibo.samplejavafx.mvc.model.chessboard.BoardObserver;
import it.unibo.samplejavafx.mvc.model.entity.Entity;
import it.unibo.samplejavafx.mvc.model.point2d.Point2D;

import java.util.function.Supplier;

/**
 * Records game events into a GameHistory.
 * Filters out redundant events generated by the internal logic of ChessBoardImpl.
 */
public final class GameHistoryRecorder implements BoardObserver {

    private static final String UNKNOWN = "Unknown";
    private final GameHistory history;
    private final Supplier<Integer> turnSupplier;

    /**
     * @param turnSupplier a supplier that provides the current turn number.
     */
    public GameHistoryRecorder(final Supplier<Integer> turnSupplier) {
        this.history = new GameHistory();
        this.turnSupplier = turnSupplier;
    }

    /**
     * @return the recorded history.
     */
    @SuppressFBWarnings("EI_EXPOSE_REP")
    public GameHistory getHistory() {
        return history;
    }

    @Override
    public void onEntityAdded(final Point2D pos, final Entity entity) {
        history.addEvent(new SpawnEvent(turnSupplier.get(), entity, pos));
    }

    @Override
    public void onEntityRemoved(final Point2D pos, final Entity entity) {
        history.addEvent(new DespawnEvent(turnSupplier.get(), entity, pos));
    }

    @Override
    public void onEntityMoved(final Point2D from, final Point2D to) {
        processMove(from, to);
    }

    @Override
    public void onEntityEaten(final Point2D from, final Point2D to) {
        processMove(from, to);
    }

    private void processMove(final Point2D from, final Point2D to) {
        String entityName = UNKNOWN;
        Entity capturedEntity = null;

        // 1. Check and remove Spawn at 'to' (The arrival of the mover)
        GameEvent last = history.getLastEvent();
        if (last instanceof SpawnEvent spawn && spawn.position().equals(to)) {
            entityName = spawn.entity().getName();
            history.removeLastEvent();
        }

        // 2. Check and remove Despawn at 'from' (The departure of the mover)
        last = history.getLastEvent();
        if (last instanceof DespawnEvent despawn && despawn.position().equals(from)) {
            // Only remove if it matches the entity name (if known) or if we assume it's the mover
            if (UNKNOWN.equals(entityName)) {
                entityName = despawn.entity().getName();
                history.removeLastEvent();
            } else if (despawn.entity().getName().equals(entityName)) {
                history.removeLastEvent();
            }
        }

        // 3. Check and remove Despawn at 'to' (The victim)
        last = history.getLastEvent();
        if (last instanceof DespawnEvent despawn && despawn.position().equals(to)) {
            capturedEntity = despawn.entity();
            history.removeLastEvent();
        }

        history.addEvent(new MoveEvent(turnSupplier.get(), entityName, from, to, capturedEntity));
    }
}
