@startuml AdvancedRules

skinparam classAttributeIconSize 0
hide empty fields
hide empty method

interface AdvancedRules {

    +{static}check()
    +{static}checkmate()
    +{static}draw()
    +{static}enPassant()
    +{static}castle()
}
@enduml