@startuml GameTimer

skinparam classAttributeIconSize 0
hide empty fields
hide empty methods

interface GameTimer {
    +start() : void
    +stop() : void
    +switchTurn() : void
    +getTimeRemaining(player : PlayerColor) : long
    +setActivePlayer(player : PlayerColor) : void
    +shutdown() : void
}

@enduml