@startuml Point2D

skinparam classAttributeIconSize 0
hide empty fields
hide empty methods

class Point2D {
    +x() : int
    +y() : int
    +sum(p : Point2D) : Point2D
    +multiply(n : int) : Point2D
    +invertX() : Point2D
    +invertY() : Point2D
    +flipY(boardHeight : int) : Point2D
}

@enduml
