@startuml TurnHandler

skinparam classAttributeIconSize 0
hide empty fields
hide empty method

interface TurnHandler {
    +thinking(pos : Point2D) : List<Point2D>
    +executeTurn(moveAction : MoveType, pos : Point2D) : boolean
    +setStartTurn(turn : int)
    +setStartPlayerColor(color : PlayerColor)
    +surrender()
    +getPromotingPawnPos() : Point2D
}

interface TurnHandlerContext {
    +thinking(pos : Point2D) : List<Point2D>
    +executeTurn() : boolean
    +transitionTo(newState : TurnState)
    +passOnPromotion(pawn : Optional<Piece>)
    +unsetCurrentPiece()
}

interface TurnState {
    +thinking(pos : Point2D) : List<Point2D>
}

class TurnHandlerImpl
TurnHandler <|.. TurnHandlerImpl
TurnHandlerContext <|.. TurnHandlerImpl
TurnHandlerImpl o-- TurnState

abstract class AbstractTurnState {
    -context : TurnHandlerContext
}
TurnState <|.. AbstractTurnState

class NormalTurnState
class CheckTurnState
class DoubleCheckTurnState
AbstractTurnState <|-- NormalTurnState
AbstractTurnState <|-- CheckTurnState
AbstractTurnState <|-- DoubleCheckTurnState
@enduml